### ISSUE TITLE
Proposed: function `gadm` remove file after downloading

### ISSUE THREAD

**Issue by LucieContamin** [choisy/sptools#1]
The function `gadm` download the last version of gadm file, is it possible to remove it after reading the file?

**Comment by LucieContamin** [comment]
Resolve in the pull-request #2

**Comment by choisy** [comment]
How about including this as an option to the function?
Additionally, we could also give the possibility to the user to save the file into a local data base so that (s)he doesn't need to download it again if (s)he need it again in the future. For that we'd need
* to include these files into the package file system on disk and
* test whether the file already exists locally at each `gadm()` call before downloading it if necessary.

**Comment by choisy** [comment]
Related to this data base issue, we need to address the following points:
* when the package is installed on disk, we want it to check whether another version of it is already installed;
* if another version is already installed, we want it to check whether it contains a data base;
* if it contains a data base, we want it to ask the user whether (s)he wants to keep the data base;
* if the user wants to keep the data base, we need to find a way to do so.

**Comment by choisy** [comment]
Addressed by pull request #30
