### ISSUE TITLE
What happens if the Raster* and Spatial* objects do not superpose?

### ISSUE THREAD

**Issue by choisy** [choisy/sptools#12]
For `resample_from_grid`, `split_on_poly` and `add_from_raster`, what happens if the `Raster*` and the `Spatial*` objects do not superpose? Does it returns an error? (I guess so). Should we include a test on that in these functions?

**Comment by LucieContamin** [comment]
I try each function with not overlapping `Raster*` and `Spatial*` object:

``` 
library(sf)
library(sp)
library(magrittr)
library(raster)

# Raster
ppp2010 <- worldpopVN::getpop(2010)
proj <- CRS(proj4string(ppp2010))
# SpatialPolygons
fr <- as_Spatial(sptools::gadm("France", "sf", 0, intlib = TRUE))
fr_a1 <- as_Spatial(sptools::gadm("France", "sf", 1, intlib = TRUE))
# SpatialPoints
gridfr <- fr %>% makegrid(100)%>% SpatialPoints(proj)
```

-  For the function `resample_from_grid` :

 ```
 resample_from_grid(ppp2010, gridfr)
 # returns an error : Error in .intersectExtent(x, y, validate = TRUE) : 
 # objects do not intersect
 ```
 The problem is that the error is print after some time so I will advice to add a test to have the error 
 more quickly:
 ```
 overlap <- try(raster::intersect(ppp2010, gridfr), silent = TRUE)
 if (class(overlap) == "try-error) stop("objects extents do not overlap") 
 ```
-  For the function `split_on_poly` :

 ```
 split_on_poly(ppp2010, fr_a1[1:3, ])
 # returns an error : Error in .intersectExtent(x, y, validate = TRUE) : 
 # objects do not intersect
 ```
 The error appears quickly (nearly direct) so I don't think we need to add a test as the message is also informative.

- For the function `add_from_raster` :

```
value <- fr %>%
  spsample(100, "random") %>%
  SpatialPointsDataFrame(data.frame(variable = 1:100)) %>%
  add_from_raster(srtmVN::getsrtm(), "elevation")
```
It returns no error but NA as value in the column `"elevation"`. I think we should add a test with an error, I propose:
```
 overlap <- try(raster::intersect(ppp2010, gridfr), silent = TRUE)
 if (class(overlap) == "try-error") stop("extents do not overlap")
```

I will add my proposition in a pull-request.
